
module.exports = {

  texts: {
    hi: "Hi {{name}}. My name is Fred\r\nWelcome to Tubet, Kenya’s 1st Fantasy betting game for the Premier League with real world odds.",
    disclaimer: "Before we continue, you need to accept our Terms and conditions. \r\n\r\n 1. You are +18. \r\n 2. This is not a betting service. \r\n 3. Any odds or suggested winnings are not guaranteed.",
    prompt: "Do you agree? 👀",
    termsRejected: "😡. Sorry, but I can't continue until you accept the terms and conditions.",
    termsAccepted: '👊',
    personalization: 'Lets get to know each other a bit. What team do you support?',
    teamSelected: "🤘",
    teamNotFound: "🤔",
    teamTryAgain: "Let me help you abit... How about you pick one from this list?",
    bettingIntro: "Ok, time for Betting 101 🔑",
    explainerBet: "Predict how a match between two teams will end and place some 💰💰💰. Get it right and, you will win the amount you placed multiplied by the *Odds*. Get it wrong = You lose. Simple right?",
    explainerQuestionOdds: "Odds! What are those?",
    explainerTest: "Test me!",
    explainerOdds: "As Odd is a number that tells you how likely something is to happen (which in our case really means how much money you will make if you predict the correct result).\r\nAn odd of 2 means you'll make 2 times your money if you are right.",
    explainerOddsExample: "Ok, let's see if you're with me.\r\n\r\n*Liverpool (Home) v Everton (Away):*\r\n_H:2.25 A:3.25 X:4.10_\r\n*BET ID: #000*",
    explainerOddsQuiz: "Which result is more likely to happen?",
    explainerOddsQuizOptions: "Liverpool Win,Everton Win,Draw",
    exampleCorrect: "👍",
    exampleWrong: "👎",
    exampleExplainer: "High odds = Less likely to happen. \r\nLower odds = More likely to happen. In ⚽, the Favorite Team will have lower odds to win than the Underdog. \r\nOk, lets talk 💰💰💰",
    creditsExplainer: "Instead of real money, we use credits in this game. Say for example if you had bet 100 credits on Liverpool to win at 2.25 and you were correct, how many credits will you have won?",
    exampleResultsCorrect: "👍, 225💰.",
    exampleResultsWrong: "👎, you should have said 225.",
    exampleResultsExplainer: "If you pick the right result, your winnings are calculated by multiplying your bet by the odds, so 100 x 2.25 = 225",
    startingCredits: "🎓 I think you are now ready to start playing. I'll start you off with 100 free credits 💰.",
    goodLuck: "Last weeks games are all done, so I'll let you know as soon as the odds are ready for this week",
    waiting: "Mmh, I'm still preparing the odds for this week. Let me holla when I'm ready",
    share: "Having fun? Its even better if you invite your Friends",
    practice: "I'm still getting my act together, but I've got one practice ⚽ available for today. Would you like to try it out? - I'll add another 100 free credits 💰",
    practiceNo: "Don't be a 🐤",
    practivePrompt: "I'm not usually this generous, but there's 100💰 extra free credits...\r\n😊",
    practiceBegin: "Ok, here we go\r\n",
    practiceRule: "Today I'll be taking only a single bet. I'm sending you the odds, right now. To place a bet, reply with the _BET ID_, then the outcome (H-Home,A-Away or X-Draw) and then the amount in credits you want to wager.",
    practiceExample: "Lets look at the previous example. \r\n\r\n*Liverpool (Home) v Everton (Away):*\r\n_H:2.25 A:3.25 X:4.10_\r\n👉*BET ID: #000*👈",
    practiceInstruction: "If I wanted to bet 100💰 for Liverpool to win, I would reply with *#000 H 100*",
    practiceLetsGo: "Easy. Lets go...",
    wrongBetId: "Oops, I can't quite understand your bet. Please try again with the format *#ID OUTCOME AMOUNT*",
    wagerAccepted: "You have bet {{amount}}💰  for a {{outcome}}. If you are right you could win {{winnings}}💰. Good luck.",
    betTooHigh: "🙊\r\nOops, you only have {{amount}}💰 available so you need to make a smaller bet."
  },

  gifs: {
    liv: "http://media3.giphy.com/media/wXsCbEJPNZGSY/200.gif",
    mun: "http://i.giphy.com/42mVGkLhOW0kU.gif",
    ars: "http://i.giphy.com/lXiRyi9qA8Xh9sYYU.gif",
    che: "http://i.giphy.com/y62tQV0Zr08OQ.gif",
    whu: "http://i.giphy.com/26CYAyjsfaOVOIfUk.gif",
    cry: "http://i.giphy.com/3o7qDMlVquZI1axqQ8.gif",
    mci: "http://i.giphy.com/l3UcicwEsOOan1Q2c.gif",
    eve: "http://i.giphy.com/12s8pTSd3ZLcLS.gif",
    tot: "http://i.giphy.com/3o6gb9BE0yfvODVPHy.gif",
    wba: "http://i.giphy.com/tBb19fkNaCazBYtWQsE.gif",
    stk: "http://stream1.gifsoup.com/view6/4882172/great-goal-of-stoke-city-goalkeeper-o.gif",
    sun: "http://i.giphy.com/26BRCp0VTMlaK5FUk.gif",
    sou: "http://i.giphy.com/XpDYwAwJs2R0s.gif",
    lei: "http://i.giphy.com/l4Ho5sWX51Mn8JAE8.gif",
    bou: "http://i.giphy.com/a8siLqtWyqzSg.gif",
    wat: "http://i.giphy.com/HQLu5sAaoDIKA.gif",
    mou: "http://media3.giphy.com/media/6eKCAGtepHvjO/200.gif"
  }
}
